import { useState } from "react";
import { ArrowUpRight, ArrowDownRight, Brain, Clock, Radio, Filter, Search, Bell, Zap, TrendingUp } from "lucide-react";

interface Signal {
  id: number;
  pair: string;
  icon: string;
  category: string;
  type: "BUY" | "SELL";
  entry: string;
  tp: string[];
  sl: string;
  timeframe: string;
  confidence: number;
  status: "ACTIVE" | "HIT TP" | "RUNNING";
  change: string;
  up: boolean;
  time: string;
}

const ALL_SIGNALS: Signal[] = [
  { id: 1, pair: "BTC/USDT", icon: "₿", category: "Crypto", type: "BUY", entry: "67,432", tp: ["68,200", "69,500", "71,000"], sl: "66,800", timeframe: "1D", confidence: 97, status: "RUNNING", change: "+4.82%", up: true, time: "2m ago" },
  { id: 2, pair: "EUR/USD", icon: "€", category: "Forex", type: "BUY", entry: "1.0842", tp: ["1.0870", "1.0895", "1.0920"], sl: "1.0815", timeframe: "4H", confidence: 94, status: "RUNNING", change: "+0.42%", up: true, time: "8m ago" },
  { id: 3, pair: "XAU/USD", icon: "Au", category: "Metals", type: "SELL", entry: "2,042.5", tp: ["2,035", "2,028", "2,020"], sl: "2,050", timeframe: "1H", confidence: 89, status: "HIT TP", change: "-0.18%", up: false, time: "14m ago" },
  { id: 4, pair: "ETH/USDT", icon: "Ξ", category: "Crypto", type: "BUY", entry: "3,482", tp: ["3,550", "3,620", "3,710"], sl: "3,420", timeframe: "4H", confidence: 92, status: "ACTIVE", change: "+6.20%", up: true, time: "22m ago" },
  { id: 5, pair: "GBP/JPY", icon: "£", category: "Forex", type: "SELL", entry: "192.84", tp: ["192.40", "191.95", "191.50"], sl: "193.30", timeframe: "15M", confidence: 86, status: "ACTIVE", change: "-0.38%", up: false, time: "31m ago" },
  { id: 6, pair: "NAS100", icon: "N", category: "Indices", type: "BUY", entry: "18,245", tp: ["18,400", "18,580", "18,750"], sl: "18,120", timeframe: "1D", confidence: 91, status: "RUNNING", change: "+1.82%", up: true, time: "44m ago" },
  { id: 7, pair: "SOL/USDT", icon: "S", category: "Crypto", type: "BUY", entry: "168.42", tp: ["174", "180", "188"], sl: "163", timeframe: "4H", confidence: 88, status: "ACTIVE", change: "+8.12%", up: true, time: "1h ago" },
  { id: 8, pair: "USD/JPY", icon: "¥", category: "Forex", type: "SELL", entry: "150.82", tp: ["150.40", "149.95", "149.50"], sl: "151.30", timeframe: "1H", confidence: 84, status: "RUNNING", change: "-0.24%", up: false, time: "1h ago" },
  { id: 9, pair: "SPX500", icon: "S", category: "Indices", type: "BUY", entry: "5,184", tp: ["5,220", "5,260", "5,310"], sl: "5,150", timeframe: "1D", confidence: 90, status: "ACTIVE", change: "+0.62%", up: true, time: "2h ago" },
];

const CATEGORIES = ["All", "Crypto", "Forex", "Metals", "Indices"];

export default function SignalsPage() {
  const [filter, setFilter] = useState("All");
  const [search, setSearch] = useState("");

  const filtered = ALL_SIGNALS.filter((s) => {
    const matchCat = filter === "All" || s.category === filter;
    const matchSearch = s.pair.toLowerCase().includes(search.toLowerCase());
    return matchCat && matchSearch;
  });

  const stats = {
    total: ALL_SIGNALS.length,
    buy: ALL_SIGNALS.filter((s) => s.type === "BUY").length,
    sell: ALL_SIGNALS.filter((s) => s.type === "SELL").length,
    avgConf: Math.round(ALL_SIGNALS.reduce((a, s) => a + s.confidence, 0) / ALL_SIGNALS.length),
  };

  return (
    <div className="pt-28 lg:pt-36 pb-20">
      <div className="max-w-7xl mx-auto px-5 sm:px-8">
        {/* Page header */}
        <div className="mb-8 lg:mb-10">
          <div className="flex items-center gap-2 mb-4">
            <span className="live-dot" />
            <span className="text-[11px] font-semibold uppercase tracking-wider text-emerald-400">Live Trading Signals</span>
          </div>
          <h1 className="font-display font-bold text-4xl sm:text-5xl lg:text-6xl tracking-tight leading-[1.05] text-white text-balance">
            Active <span className="font-serif italic text-gradient-gold">signals</span>, delivered in real time
          </h1>
          <p className="mt-4 text-ink-300 text-base lg:text-lg max-w-2xl">
            Every signal includes validated entry, multiple take-profit levels, and stop-loss — generated by our neural engine.
          </p>
        </div>

        {/* Stats strip */}
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 mb-8">
          <StatBox label="Active signals" value={stats.total.toString()} icon={Radio} accent="text-emerald-400" />
          <StatBox label="Buy signals" value={stats.buy.toString()} icon={TrendingUp} accent="text-emerald-400" />
          <StatBox label="Sell signals" value={stats.sell.toString()} icon={ArrowDownRight} accent="text-rose-400" />
          <StatBox label="Avg confidence" value={`${stats.avgConf}%`} icon={Brain} accent="text-violet-400" />
        </div>

        {/* Toolbar */}
        <div className="glass rounded-2xl p-3 mb-6 flex flex-col sm:flex-row gap-3 border border-white/5">
          <div className="flex-1 relative">
            <Search className="w-4 h-4 absolute left-3 top-1/2 -translate-y-1/2 text-ink-500" />
            <input
              type="text"
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              placeholder="Search pairs (e.g. BTC, EUR)"
              className="w-full bg-white/[0.03] border border-white/5 rounded-lg pl-10 pr-4 py-2.5 text-sm text-white placeholder:text-ink-500 focus:outline-none focus:border-amber-400/40"
            />
          </div>
          <div className="flex items-center gap-1.5 overflow-x-auto scrollbar-thin">
            {CATEGORIES.map((c) => (
              <button
                key={c}
                onClick={() => setFilter(c)}
                className={`px-4 py-2 text-xs font-semibold rounded-lg whitespace-nowrap transition-all ${
                  filter === c
                    ? "bg-white/10 text-white border border-white/10"
                    : "text-ink-400 hover:text-white hover:bg-white/5 border border-transparent"
                }`}
              >
                {c}
              </button>
            ))}
          </div>
          <button className="btn-secondary text-xs font-semibold px-4 py-2.5 rounded-lg flex items-center gap-1.5 whitespace-nowrap">
            <Filter className="w-3.5 h-3.5" />
            More
          </button>
        </div>

        {/* Signal list */}
        <div className="grid md:grid-cols-2 gap-4 stagger">
          {filtered.map((s) => (
            <SignalRow key={s.id} signal={s} />
          ))}
        </div>

        {filtered.length === 0 && (
          <div className="text-center py-20 text-ink-400">
            <Filter className="w-10 h-10 mx-auto mb-3 opacity-50" />
            <div className="font-display text-lg text-white">No signals match your filter</div>
            <div className="text-sm mt-1">Try a different category or clear the search.</div>
          </div>
        )}

        {/* Subscribe CTA */}
        <div className="mt-12 rounded-2xl border border-white/10 p-6 lg:p-8 bg-gradient-to-br from-amber-900/10 via-ink-900 to-teal-900/10 relative overflow-hidden">
          <div className="absolute inset-0 grid-bg opacity-30" />
          <div className="relative flex flex-col lg:flex-row items-start lg:items-center justify-between gap-4">
            <div>
              <div className="flex items-center gap-2 mb-2">
                <Bell className="w-4 h-4 text-amber-400" />
                <span className="text-[11px] font-semibold uppercase tracking-wider text-amber-400">Get every signal</span>
              </div>
              <h3 className="font-display text-xl lg:text-2xl font-bold text-white">
                Receive instant alerts via Telegram, Discord, or SMS
              </h3>
              <p className="text-sm text-ink-300 mt-1">Never miss a high-confidence trade setup again.</p>
            </div>
            <button className="btn-primary text-sm px-5 py-3 rounded-lg inline-flex items-center gap-1.5 whitespace-nowrap">
              <Zap className="w-4 h-4" />
              Enable notifications
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

function StatBox({ label, value, icon: Icon, accent }: any) {
  return (
    <div className="card rounded-2xl p-4 lg:p-5">
      <div className="flex items-center gap-2 mb-2">
        <Icon className={`w-4 h-4 ${accent}`} />
        <span className="text-[10px] uppercase tracking-wider text-ink-400">{label}</span>
      </div>
      <div className="font-display font-bold text-2xl lg:text-3xl text-white">{value}</div>
    </div>
  );
}

function SignalRow({ signal }: { signal: Signal }) {
  const isBuy = signal.type === "BUY";
  return (
    <div className="card rounded-2xl p-5 group">
      {/* Top */}
      <div className="flex items-start justify-between mb-4">
        <div className="flex items-center gap-3">
          <div className="w-11 h-11 rounded-xl bg-white/[0.04] border border-white/5 flex items-center justify-center font-bold text-white">
            {signal.icon}
          </div>
          <div>
            <div className="flex items-center gap-2">
              <span className="font-display font-semibold text-base text-white">{signal.pair}</span>
              <span className={`text-[9px] font-bold uppercase tracking-wider px-1.5 py-0.5 rounded ${
                isBuy ? "bg-emerald-500/15 text-emerald-400" : "bg-rose-500/15 text-rose-400"
              }`}>
                {signal.type}
              </span>
            </div>
            <div className="flex items-center gap-2 mt-1 text-[10px] text-ink-400">
              <span>{signal.category}</span>
              <span>·</span>
              <span>{signal.timeframe}</span>
              <span>·</span>
              <span className="flex items-center gap-1"><Clock className="w-2.5 h-2.5" />{signal.time}</span>
            </div>
          </div>
        </div>
        <div className={`flex items-center gap-0.5 text-xs font-semibold ${signal.up ? "text-emerald-400" : "text-rose-400"}`}>
          {signal.up ? <ArrowUpRight className="w-3.5 h-3.5" /> : <ArrowDownRight className="w-3.5 h-3.5" />}
          {signal.change}
        </div>
      </div>

      {/* Entry / TP / SL */}
      <div className="grid grid-cols-5 gap-2 mb-4">
        <div className="rounded-lg bg-white/[0.02] border border-white/5 p-2.5 col-span-2">
          <div className="text-[9px] text-ink-400 uppercase tracking-wider">Entry</div>
          <div className="font-mono font-semibold text-sm text-white mt-0.5">{signal.entry}</div>
        </div>
        {signal.tp.slice(0, 2).map((t, i) => (
          <div key={i} className="rounded-lg bg-emerald-500/[0.04] border border-emerald-500/10 p-2.5">
            <div className="text-[9px] text-emerald-400/70 uppercase tracking-wider">TP{i + 1}</div>
            <div className="font-mono font-semibold text-sm text-emerald-300 mt-0.5">{t}</div>
          </div>
        ))}
        <div className="rounded-lg bg-rose-500/[0.04] border border-rose-500/10 p-2.5">
          <div className="text-[9px] text-rose-400/70 uppercase tracking-wider">SL</div>
          <div className="font-mono font-semibold text-sm text-rose-300 mt-0.5">{signal.sl}</div>
        </div>
      </div>

      {/* Confidence bar */}
      <div className="flex items-center justify-between mb-1.5">
        <span className="flex items-center gap-1.5 text-[11px] text-ink-400">
          <Brain className="w-3 h-3 text-violet-400" />
          AI Confidence
        </span>
        <span className="text-[11px] font-semibold text-white">{signal.confidence}%</span>
      </div>
      <div className="h-1 bg-white/5 rounded-full overflow-hidden mb-4">
        <div
          className="h-full bg-gradient-to-r from-amber-400 to-amber-600 rounded-full"
          style={{ width: `${signal.confidence}%` }}
        />
      </div>

      {/* Actions */}
      <div className="flex items-center gap-2">
        <button className={`flex-1 py-2.5 rounded-lg text-xs font-semibold uppercase tracking-wider transition-all ${
          isBuy
            ? "bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 hover:bg-emerald-500/15"
            : "bg-rose-500/10 text-rose-400 border border-rose-500/20 hover:bg-rose-500/15"
        }`}>
          Follow {signal.type}
        </button>
        <button className="px-4 py-2.5 rounded-lg text-xs font-semibold text-ink-300 hover:text-white bg-white/[0.03] border border-white/5 hover:border-white/10 transition-all">
          Details
        </button>
      </div>
    </div>
  );
}
